[mqtt]
broker = 192.168.1.100
port = 1883
# this is the base topic for all mower related messages, the actual topic for each mower will be derived from this by appending the mower name and message type, e.g. gardena/automower/mower_1/status or gardena/automower/mower_2/cmd
# e.g. gardena/automower/mower_1/status
topic_base = gardena/automower

[system]
log_level = INFO
poll_active = 60
poll_idle = 900

# First mower configuration
[mower_1]
name = Minimo Vorn
address = AA:BB:CC:DD:EE:FF
pin = 0000

# Second mower configuration (arbitrary number of additional mowers can be added)
[mower_2]
name = Minimo Hinten
address = 11:22:33:44:55:66
pin = 1111